apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-cert-manager-operator
  namespace: {{ .Release.Namespace }}
spec:
  targetNamespaces:
    - {{ .Release.Namespace }}
